language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
# command to run tests
script: python run_tests.py